server:
    port: 8082

# 28181 SIP服务器的配置
sip-server:
    # [必须修改] 本机的IP
    ip: 192.168.1.6
    # 28181服务监听的端口
    port: 8116
    # 根据国标6.1.2中规定，domain宜采用ID统一编码的前十位编码。国标附录D中定义前8位为中心编码（由省级、市级、区级、基层编号组成，参照GB/T 2260-2007）
    # 后两位为行业编码，定义参照附录D.3
    # 3701020049标识山东济南历下区 信息行业接入
    domain: ${WVP_DOMAIN:4101050000}
    id: ${WVP_ID:41010500002000000001}
    # [可选] 默认设备认证密码，后续扩展使用设备单独密码, 移除密码将不进行校验
    password: ${WVP_PWD:admin123}
    #心跳周期
    keepaliveTimeOut: 30

#作为28181设备的配置
sip-device:
    # [必须修改] 本机的IP
    ip: 192.168.1.6
    # 28181服务监听的端口
    port: 5080
    #
    id: 64010000001110000001
    #默认设备认证密码
    password: admin123

ffmpeg:
    #ffmpeg执行文件路径
    path: /opt/homebrew/bin/ffmpeg
    #模拟推送视频流的命令
    pushStreamCmd: -re -i {filePath} -an -c:v libx264 -preset ultrafast -tune zerolatency -g 25 -keyint_min 25 -x264-params repeat-headers=1:scenecut=0 -pix_fmt yuv420p -payload_type {payloadType} -ssrc {ssrc} -f rtp rtp://{ip}:{port}
